name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests in Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build and start Docker Compose
        working-directory: Proyecto_final_calidad/Proyecto_final_calidad
        run: docker compose -f docker-compose-sencillo.yml up -d --build

      - name: Wait for app to be healthy
        run: |
          timeout 60 sh -c 'until curl -s http://localhost:8080/actuator/health | grep UP; do sleep 2; done'

      - name: Run Gradle tests
        working-directory: Proyecto_final_calidad/Proyecto_final_calidad
        run: ./gradlew test

      - name: Stop containers
        if: always()
        working-directory: Proyecto_final_calidad/Proyecto_final_calidad
        run: docker compose -f docker-compose-sencillo.yml down
