name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests in Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build and start Docker Compose (including tests)
        working-directory: Proyecto_final_calidad/Proyecto_final_calidad
        run: |
          docker compose -f docker-compose-basico.yml up --build --abort-on-container-exit

      - name: Stop containers
        if: always()
        working-directory: Proyecto_final_calidad/Proyecto_final_calidad
        run: docker compose -f docker-compose-basico.yml down
