name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: proyecto_final_calidad
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: letmein
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Playwright Browsers
        run: npx playwright install

      # <-- NUEVO: instalar dependencias necesarias para que Playwright funcione en Linux -->
      - name: Install Playwright Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwoff1 libvpx9 libevent-2.1-7t64 libopus0 \
            libgstreamer-plugins-base1.0-0 libgstreamer-gl1.0-0 libgstreamer-plugins-bad1.0-0 \
            libharfbuzz-icu0 libsecret-1-0 libhyphen0 libmanette-0.2-0 libflite1 libgles2 \
            gstreamer1.0-libav

      - name: Wait for DB
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Esperando DB..."
            sleep 2
          done

      - name: Grant gradlew execution permissions
        run: chmod +x ./Proyecto_final_calidad/Proyecto_final_calidad/gradlew

      # <-- NUEVO: levantar la app antes de ejecutar tests -->
      - name: Start Spring Boot app
        run: ./gradlew bootRun &
        working-directory: ./Proyecto_final_calidad/Proyecto_final_calidad

      - name: Wait for Spring Boot to be ready
        run: |
          until curl -s http://localhost:8080/actuator/health | grep UP; do
            echo "Esperando Spring Boot..."
            sleep 2
          done

      - name: Run tests
        run: ./gradlew test --info --console=plain
        working-directory: ./Proyecto_final_calidad/Proyecto_final_calidad

